// Link: https://leetcode.com/problems/median-of-two-sorted-arrays/description/

// Suggested improvement, generated by lcagent's improver agent.
// Review before adopting — this is a suggestion, not your work.
#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        // Ensure nums1 is the smaller array to get O(log min(m,n))
        if (nums1.size() > nums2.size()) return findMedianSortedArrays(nums2, nums1);
        int m = nums1.size(), n = nums2.size();
        int totalLeft = (m + n + 1) / 2; // number of elements on left side of partition

        int lo = 0, hi = m;
        while (lo <= hi) {
            int i = (lo + hi) / 2;          // partition in nums1
            int j = totalLeft - i;          // corresponding partition in nums2

            int nums1Left  = (i == 0) ? INT_MIN : nums1[i - 1];
            int nums1Right = (i == m) ? INT_MAX : nums1[i];
            int nums2Left  = (j == 0) ? INT_MIN : nums2[j - 1];
            int nums2Right = (j == n) ? INT_MAX : nums2[j];

            // Check if we have found correct partition
            if (nums1Left <= nums2Right && nums2Left <= nums1Right) {
                // If total length is odd, median is max of left parts
                if ((m + n) % 2 == 1)
                    return (double)max(nums1Left, nums2Left);
                // Even length: average of max left and min right
                return ((double)max(nums1Left, nums2Left) + min(nums1Right, nums2Right)) / 2.0;
            }
            // If left part of nums1 is too big, move hi left
            else if (nums1Left > nums2Right) {
                hi = i - 1;
            }
            // Else left part of nums2 is too big, move lo right
            else {
                lo = i + 1;
            }
        }
        // Should never reach here if input arrays are valid
        return 0.0;
    }
};
