// Link: https://leetcode.com/problems/magical-string/description/

#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    // TC: O(n), SC: O(n)
    // Approach:
    //  1. The magical string is generated by reading the previous elements and determining how many times to repeat the next value (1 or 2).
    //  2. We maintain a count of '1's as we build the string up to the desired length n.
    //  3. We use two pointers: head to read the current run length and tail to fill in the next values in the string.
    //  4. We alternate between 1 and 2 for the next value to be added based on the last value added to the string.
    //  5. The process continues until we have filled the string up to length n, and we return the count of '1's encountered during this process.
    // 6. The function handles edge cases for n <= 0 and n <= 3 directly, returning the appropriate count of '1's.
    int magicalString(int n)
    {
        if (n <= 0)
            return 0;
        if (n <= 3)
            return 1; // "122" -> only one '1'

        vector<int> arr(n);
        arr[0] = 1;
        arr[1] = 2;
        arr[2] = 2;

        int count = 1; // count of '1's so far (arr[0] = 1)
        int head = 2;  // points to element telling us the next run length
        int tail = 3;  // next index to fill in

        while (tail < n)
        {
            int nextVal = 3 - arr[tail - 1]; // alternate between 1 and 2
            int groupLen = arr[head];        // how many times to repeat nextVal

            for (int i = 0; i < groupLen && tail < n; i++)
            {
                arr[tail] = nextVal;
                if (nextVal == 1)
                    count++;
                tail++;
            }
            head++;
        }

        return count;
    }
};